using LethalConfig.Mods;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.EventSystems;

namespace LethalConfig.MonoBehaviours
{
    internal class ModList : MonoBehaviour
    {
        public GameObject modItemPrefab;
        public GameObject listContainerObject;

        public ConfigList configList;
        public DescriptionBox descriptionBox;

        private List<ModListItem> _items;

        private void Awake()
        {
            _items = new List<ModListItem>();
            BuildModList();
        }

        private void BuildModList()
        {
            _items.Clear();
            foreach (Transform child in listContainerObject.transform)
            {
                Destroy(child.gameObject);
            }

            var mods = LethalConfigManager.Mods.Values
                .OrderBy(m => m.modInfo.GUID != PluginInfo.Guid)
                .ThenBy(m => m.IsAutoGenerated)
                .ThenBy(m => m.modInfo.Name);

            foreach (var mod in mods)
            {
                var modItem = Instantiate(modItemPrefab, listContainerObject.transform);
                modItem.transform.localScale = Vector3.one;
                modItem.transform.localPosition = Vector3.zero;
                modItem.transform.localRotation = Quaternion.identity;
                var listItem = modItem.GetComponent<ModListItem>();
                listItem.mod = mod;
                listItem.modSelected += ModSelected;
                listItem.OnHoverEnter += () =>
                {
                    descriptionBox.ShowModInfo(mod);
                    ConfigMenuManager.Instance.menuAudio.PlayHoverSFX();
                };
                listItem.OnHoverExit += () =>
                {
                    descriptionBox.HideModInfo();
                };
                _items.Add(modItem.GetComponent<ModListItem>());
            }
        }

        private void ModSelected(Mod mod)
        {
            ConfigMenuManager.Instance.menuAudio.PlayConfirmSFX();
            configList.LoadConfigsForMod(mod);

            _items.First(i => i.mod == mod).SetSelected(true);

            foreach (var item in _items.Where(i => i.mod != mod))
                item.SetSelected(false);
        }
    } 
}
