using LethalConfig.ConfigItems;
using LethalConfig.Utils;
using SharedUtils;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;

namespace LethalConfig.MonoBehaviours.Components
{
    internal abstract class ModConfigController : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler
    {
        protected BaseConfigItem baseConfigItem;

        internal ConfigMenuAudioManager audioManager;

        public delegate void OnHoverHandler();
        public event OnHoverHandler OnHoverEnter;
        public event OnHoverHandler OnHoverExit;

        protected bool isOnSetup = false;

        public TextMeshProUGUI nameTextComponent;

        public virtual bool SetConfigItem(BaseConfigItem configItem)
        {
            this.baseConfigItem = configItem;
            isOnSetup = true;
            this.OnSetConfigItem();
            isOnSetup = false;
            return true;
        }

        protected abstract void OnSetConfigItem();
        public virtual void UpdateAppearance()
        {
            nameTextComponent.text = $"{(baseConfigItem.HasValueChanged ? "* " : "")}{baseConfigItem.Name}";
        }

        public virtual void ResetToDefault()
        {
            audioManager.PlayConfirmSFX();
            baseConfigItem.ChangeToDefault();
            UpdateAppearance();
        }

        public virtual string GetDescription()
        {
            var description = $"<b>{baseConfigItem.Name}</b>";

            if (baseConfigItem.IsAutoGenerated) description += "\n\n<b>*This config entry was automatically generated and may require a restart*</b>";
            else if (baseConfigItem.RequiresRestart) description += "\n\n<b>*REQUIRES RESTART*</b>";

            return description + $"\n\n{baseConfigItem.Description}";
        }

        public void OnPointerEnter(PointerEventData eventData)
        {
            OnHoverEnter();
            audioManager.PlayHoverSFX();
        }

        public void OnPointerExit(PointerEventData eventData)
        {
            OnHoverExit();
        }
    }

    internal abstract class ModConfigController<T, V> : ModConfigController where T : BaseValueConfigItem<V>
    {
        public T ConfigItem => (T)baseConfigItem;

        public override string GetDescription()
        {
            return $"{base.GetDescription()}\n\nDefault: {ConfigItem.Defaultvalue}";
        }

        public override bool SetConfigItem(BaseConfigItem configItem)
        {
            if (configItem is not T)
            {
                LogUtils.LogError($"Expected config item of type {typeof(T).Name}, but got {configItem.GetType().Name} instead.");
                return false;
            }

            return base.SetConfigItem(configItem);
        }
    } 
}
